branch-defaults:
  cicleci:
    environment: production
  default:
    environment: production
    group_suffix: null
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: music-suggestion-tool
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
