# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/Spotify-Music-suggestion-tool

    steps:

      # make git checkout
      - checkout:
          path: ~/Spotify-Music-suggestion-tool

      # install project dependencies
      - run: 
         name: "Running npm install"
         command: cd music-suggestion-tool && npm install

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "music-suggestion-tool/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "music-suggestion-tool/package.json" }}
        
      # run tests!
      - run: 
         name: "Running testing"
         command: cd music-suggestion-tool && npm test


      - run: 
          name: "Instaling linux packages dependencies"
          command: |
              sudo apt-get update && sudo apt-get install -y python-dev
              sudo curl -O https://bootstrap.pypa.io/get-pip.py
              sudo python get-pip.py
              sudo pip install awscli --upgrade
      # run s3 deploy
      #- run: 
      #    name: "Deploy react js app to AWS"
      #    command: |
      #      cd music-suggestion-tool && aws s3 ls
      #      cd music-suggestion-tool && yarn run deploy  

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "music-suggestion-tool-api/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
         paths:
            - node_modules
         key: v1-dependencies-{{ checksum "music-suggestion-tool-api/package.json" }}
      - run: 
          name: "Instaling npm packages dependencies"
          command: cd music-suggestion-tool-api && npm install
      - run:
          name: "Installing awsebcli dependencies"
          command: |
                sudo apt-get update && sudo apt-get install -y python-dev build-essential
                sudo curl -O https://bootstrap.pypa.io/get-pip.py
                sudo python get-pip.py
                sudo pip install awsebcli --upgrade
      - run:
          name: "Deploy node API to AWS"
          command: "cd music-suggestion-tool-api && eb deploy --profile default"